[package]
name = "example"
version = "0.1.0"
edition = "2021"

[dependencies]
spaxum = { path = "../spaxum" }
axum = { version = "0.8" }
tokio = { version = "1.0", features = ["rt-multi-thread"] }

[build-dependencies]
spaxum = { path = "../spaxum" }
